// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNEWCMNe0tZRTObwuU1a66LMhHeom70w',
    appId: '1:837515316023:android:4f336c52995ee8f865e8b2',
    messagingSenderId: '837515316023',
    projectId: 'couponey-fcm-a7d2b',
    storageBucket: 'couponey-fcm-a7d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0b8Ew9k_2MbXM_FXs2KblvE2YTDm1aCE',
    appId: '1:837515316023:ios:e6e61da145ba7eb465e8b2',
    messagingSenderId: '837515316023',
    projectId: 'couponey-fcm-a7d2b',
    storageBucket: 'couponey-fcm-a7d2b.firebasestorage.app',
    iosBundleId: 'com.coupon.coupondiscount',
  );
}